[workspace]
dependencies_update = true
changelog_update = true
pr_labels = ["release"]
semver_check = true
publish_timeout = "10m" # set a timeout for `cargo publish`
git_tag_enable = false
git_release_enable = false
publish = false
repo_url = "https://github.com/demml/scouter"

[[package]]
name = "scouter-dataframe"
publish = true

[[package]]
name = "scouter-evaluate"
publish = true

[[package]]
name = "scouter-dispatch"
publish = true

[[package]]
name = "scouter-drift"
publish = true

[[package]]
name = "scouter-events"
publish = true

[[package]]
name = "scouter-observability"
publish = true

[[package]]
name = "scouter-profile"
publish = true

[[package]]
name = "scouter-settings"
publish = true

[[package]]
name = "scouter-semver"
publish = true

[[package]]
name = "scouter-types"
publish = true

[[package]]
name = "scouter-sql"
publish = true

[[package]]
name = "scouter-client"
publish = true

[[package]]
name = "scouter-evaluate"
publish = true

[[package]]
name = "scouter-state"
publish = true

