[package]
name = "scouter-macro"
version = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }

[lib]
proc-macro = false

license = "MIT"
description = "Macro utilities for scouter"


[dependencies]
thiserror = { workspace = true }